
language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    # dev build is currently taking forever on hhvm so we are skipping for now
    #- SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  flowdock:
    secure: RJyC2+xYZNQvAk4+O/+r4qiN4CPzO4+Er0YDlcpZcBOcK2xlriPjpgInV8nrSYvuQYMPzk8i+n283U45sAkM/wTyz8O644sxcmV8YcjxqYL1JfHWk8Xjl8BK7c7LQ+j0bm68rIfvXhCMff6YxGU5k0OJWEOo8sKDBfWU8DD7cZs=
