devtrw_state_bridge_get_entity_state:
  path:         /state/{name}/{id}.{_format}
  requirements: { _format: xml|json|jsonp, id: \d+ }
  defaults:
    _controller: devtrw_state_bridge.controller.state:indexAction
    _format    : jsonp
    name       : primary

devtrw_state_bridge_get_state:
  path:         /state/{name}.{_format}
  requirements: { format: xml|json|jsonp }
  defaults:
    _controller: devtrw_state_bridge.controller.state:indexAction
    _format    : jsonp
    name       : primary



