parameters:
    devtrw_state_bridge_bundle.state_bridge.class: Devtrw\StateBridgeBundle\StateBridge

services:
    devtrw_state_bridge_bundle.state_bridge:
        class: %devtrw_state_bridge_bundle.state_bridge.class%
        arguments:
          - %devtrw_states%
          - @security.context
          - @request_stack

